from __future__ import annotations

import argparse
import os
import sys
import time
from datetime import datetime
from typing import Any

import yaml
import torch
import numpy as np


THIS_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(THIS_DIR)


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Infer contact-sampler hyperparameters from extracted real contact masks and "
            "save them into a YAML file."
        )
    )
    parser.add_argument(
        "--real-masks-path",
        type=str,
        default=os.path.join(PROJECT_ROOT, "contact_gen", "contact_points_validate.pt"),
        help="Path to payload generated by extract_contact_points.py",
    )
    parser.add_argument(
        "--robot-names",
        type=str,
        nargs="*",
        default=["allegro", "barrett", "ezgripper", "robotiq_3finger", "shadowhand"],
        help="Robots to infer. Must match robot_name in extracted payload samples.",
    )
    parser.add_argument(
        "--num-surface-points",
        type=int,
        default=-1,
        help="Whole-hand point count. -1 means infer from real masks per robot.",
    )
    parser.add_argument(
        "--max-real-per-robot",
        type=int,
        default=-1,
        help="Optional cap for real-mask samples per robot; -1 for all.",
    )
    parser.add_argument(
        "--output-yaml",
        type=str,
        default=os.path.join(PROJECT_ROOT, "contact_gen", "contact_sampler_hparams.yaml"),
        help="Output YAML path.",
    )
    parser.add_argument(
        "--vis-components",
        action="store_true",
        help="Open viewer for connected components of extracted contact masks.",
    )
    parser.add_argument("--vis-host", type=str, default="127.0.0.1")
    parser.add_argument("--vis-port", type=int, default=8094)
    parser.add_argument("--vis-point-size", type=float, default=0.0025)
    parser.add_argument("--vis-hand-opacity", type=float, default=0.35)
    return parser


def _resolve_robot_model_name(robot_name: str, asset_names: set[str], hint: str | None) -> str:
    if hint is not None and hint in asset_names:
        return hint
    if robot_name in asset_names:
        return robot_name
    preferred = {
        "allegro": ["dro/allegro/allegro_hand_left_extended", "dro/allegro/allegro_hand_left"],
        "barrett": ["dro/barrett/model_extended", "dro/barrett/model"],
        "ezgripper": ["dro/ezgripper/ezgripper_extended", "dro/ezgripper/ezgripper"],
        "robotiq_3finger": [
            "dro/urdf/robotiq_3finger_description_extended",
            "dro/urdf/robotiq_3finger_description",
        ],
        "shadowhand": ["dro/shadowhand/shadow_hand_right_extended", "dro/shadowhand/shadow_hand_right"],
    }
    for c in preferred.get(robot_name, []):
        if c in asset_names:
            return c
    candidates = [k for k in asset_names if (f"/{robot_name}/" in k) or (robot_name in k)]
    if len(candidates) == 0:
        raise KeyError(f"Cannot resolve robot model for '{robot_name}'")
    candidates = sorted(
        candidates,
        key=lambda x: (int(x.startswith("dro/")), int("extended" in x), int("right" in x), -len(x)),
        reverse=True,
    )
    return candidates[0]


def _mask_component_labels(mask: torch.Tensor, neighbors: list[list[int]]) -> tuple[torch.Tensor, int]:
    m = torch.as_tensor(mask).bool().view(-1).cpu().numpy()
    n = int(m.shape[0])
    labels = np.full((n,), -1, dtype=np.int64)
    if n == 0 or int(m.sum()) == 0:
        return torch.tensor(labels, dtype=torch.long), 0
    if len(neighbors) != n:
        raise RuntimeError(
            f"Mask length ({n}) does not match graph length ({len(neighbors)}). "
            "Regenerate masks or ensure surface template consistency."
        )

    comp_id = 0
    for root in np.where(m)[0].tolist():
        if labels[root] >= 0:
            continue
        labels[root] = comp_id
        stack = [int(root)]
        while stack:
            i = stack.pop()
            for j in neighbors[i]:
                j = int(j)
                if j < 0 or j >= n:
                    continue
                if (not m[j]) or (labels[j] >= 0):
                    continue
                labels[j] = comp_id
                stack.append(j)
        comp_id += 1
    return torch.tensor(labels, dtype=torch.long), int(comp_id)


def _palette_rgb(k: int) -> np.ndarray:
    if k <= 0:
        return np.zeros((0, 3), dtype=np.float32)
    import colorsys

    out = np.zeros((k, 3), dtype=np.float32)
    for i in range(k):
        h = float(i) / float(max(1, k))
        s = 0.85
        v = 1.0
        r, g, b = colorsys.hsv_to_rgb(h, s, v)
        out[i] = np.array([r, g, b], dtype=np.float32)
    return out


def _visualize_contact_components(
    vis_payload: dict[str, dict[str, Any]],
    host: str,
    port: int,
    point_size: float,
    hand_opacity: float,
) -> None:
    import viser

    if len(vis_payload) == 0:
        raise RuntimeError("No data for visualization.")

    robot_names = sorted(vis_payload.keys())
    max_samples = max(len(vis_payload[r]["samples"]) for r in robot_names)
    max_components = max(
        max((int(s["num_components"]) for s in vis_payload[r]["samples"]), default=0)
        for r in robot_names
    )
    max_samples = max(1, int(max_samples))
    max_components = max(1, int(max_components))

    server = viser.ViserServer(host=host, port=int(port))
    robot_slider = server.gui.add_slider(
        "robot_index",
        min=0,
        max=max(0, len(robot_names) - 1),
        step=1,
        initial_value=0,
    )
    sample_slider = server.gui.add_slider(
        "sample_index",
        min=0,
        max=max_samples - 1,
        step=1,
        initial_value=0,
    )
    mode_slider = server.gui.add_slider(
        "vis_mode (0=together,1=single_component)",
        min=0,
        max=1,
        step=1,
        initial_value=0,
    )
    component_slider = server.gui.add_slider(
        "component_index",
        min=0,
        max=max_components - 1,
        step=1,
        initial_value=0,
    )
    show_mesh = server.gui.add_checkbox("show_hand_mesh", initial_value=True)

    def _render() -> None:
        rname = robot_names[int(robot_slider.value)]
        robot_data = vis_payload[rname]
        samples = robot_data["samples"]
        if len(samples) == 0:
            return

        sidx = int(max(0, min(int(sample_slider.value), len(samples) - 1)))
        sample = samples[sidx]
        model = robot_data["model"]
        q = sample["q"]
        points = sample["points"].detach().cpu()
        labels = sample["component_labels"].detach().cpu().numpy().astype(np.int64)
        n_comp = int(sample["num_components"])
        vis_mode = int(mode_slider.value)
        selected_comp = int(max(0, min(int(component_slider.value), max(0, n_comp - 1))))

        mesh = model.get_trimesh_q(q, mode="original")["visual"]
        if bool(show_mesh.value) and len(mesh.vertices) > 0:
            center = torch.tensor(mesh.vertices, dtype=torch.float32).mean(dim=0, keepdim=True)
        else:
            center = points.mean(dim=0, keepdim=True)
        points_vis = points - center

        if vis_mode == 0:
            # Show all active components at once.
            pal = _palette_rgb(max(1, n_comp))
            valid = labels >= 0
            points_draw = points_vis[torch.from_numpy(valid)]
            colors = np.zeros((int(valid.sum()), 3), dtype=np.float32)
            if int(valid.sum()) > 0:
                cids = labels[valid]
                colors = pal[cids % pal.shape[0]]
        else:
            # Show selected component only.
            if n_comp <= 0:
                points_draw = torch.zeros((0, 3), dtype=torch.float32)
                colors = np.zeros((0, 3), dtype=np.float32)
            else:
                sel = labels == selected_comp
                points_draw = points_vis[torch.from_numpy(sel)]
                colors = np.tile(np.array([[1.0, 0.25, 0.15]], dtype=np.float32), (int(sel.sum()), 1))

        server.scene.add_point_cloud(
            name="contact_components",
            points=points_draw.numpy().astype(np.float32),
            colors=colors,
            point_size=float(point_size),
            point_shape="circle",
        )

        if bool(show_mesh.value) and len(mesh.vertices) > 0:
            v = torch.tensor(mesh.vertices, dtype=torch.float32) - center
            f = torch.tensor(mesh.faces, dtype=torch.int32)
            server.scene.add_mesh_simple(
                name="hand_mesh",
                vertices=v.numpy(),
                faces=f.numpy(),
                color=(0.82, 0.82, 0.82),
                opacity=float(hand_opacity),
            )
        else:
            server.scene.add_mesh_simple(
                name="hand_mesh",
                vertices=np.zeros((0, 3), dtype=np.float32),
                faces=np.zeros((0, 3), dtype=np.int32),
                color=(0.0, 0.0, 0.0),
                opacity=0.0,
            )

        print(
            f"[comp-vis] robot={rname} sample={sidx}/{len(samples)-1} "
            f"components={n_comp} vis_mode={vis_mode} selected_component={selected_comp} "
            f"points_draw={int(points_draw.shape[0])}"
        )

    @robot_slider.on_update
    def _(_: Any) -> None:
        _render()

    @sample_slider.on_update
    def _(_: Any) -> None:
        _render()

    @mode_slider.on_update
    def _(_: Any) -> None:
        _render()

    @component_slider.on_update
    def _(_: Any) -> None:
        _render()

    @show_mesh.on_update
    def _(_: Any) -> None:
        _render()

    _render()
    print(f"Contact component viewer URL: http://{host}:{port}")
    while True:
        time.sleep(1.0)


def main() -> None:
    args = _build_parser().parse_args()
    real_masks_path = os.path.abspath(args.real_masks_path)
    if not os.path.exists(real_masks_path):
        raise FileNotFoundError(f"--real-masks-path not found: {real_masks_path}")

    payload_real = torch.load(real_masks_path, map_location="cpu")
    if "samples" not in payload_real:
        raise KeyError(f"Expected 'samples' in {real_masks_path}")
    real_samples = list(payload_real["samples"])
    if len(real_samples) == 0:
        raise RuntimeError(f"No samples in {real_masks_path}")

    selected_robots = set(args.robot_names)
    by_robot: dict[str, list[dict[str, Any]]] = {r: [] for r in args.robot_names}
    for s in real_samples:
        robot_name = str(s["robot_name"])
        if robot_name not in selected_robots:
            continue
        by_robot[robot_name].append(s)

    sys.path.append(PROJECT_ROOT)
    from robot_model.robot_model import create_robot_model, discover_robot_assets  # type: ignore

    assets_meta = discover_robot_assets()
    asset_names = set(assets_meta.keys())

    out: dict[str, Any] = {
        "meta": {
            "created_at": datetime.now().isoformat(timespec="seconds"),
            "real_masks_path": real_masks_path,
            "source": "extract_contact_points.py",
            "method": "fit from real masks only; used later for data-less random generation",
        },
        "robots": {},
    }
    vis_payload: dict[str, dict[str, Any]] = {}
    for robot_name in args.robot_names:
        samples = by_robot.get(robot_name, [])
        if len(samples) == 0:
            print(f"[skip] {robot_name}: no real-mask samples found")
            continue
        if int(args.max_real_per_robot) > 0:
            samples = samples[: int(args.max_real_per_robot)]

        first_len = int(torch.as_tensor(samples[0]["hand_contact_mask"]).numel())
        if int(args.num_surface_points) > 0 and int(args.num_surface_points) != first_len:
            raise ValueError(
                f"{robot_name}: --num-surface-points={args.num_surface_points} "
                f"does not match real mask length={first_len}"
            )
        num_surface_points = first_len if int(args.num_surface_points) <= 0 else int(args.num_surface_points)

        hint = samples[0].get("robot_model_name", None)
        resolved_robot_name = _resolve_robot_model_name(robot_name, asset_names, None if hint is None else str(hint))
        model = create_robot_model(
            robot_name=resolved_robot_name,
            device=torch.device("cpu"),
            num_points=int(num_surface_points),
        )
        model_template_hash = model.get_surface_template_hash()

        real_template_hashes = set()
        real_masks_list = []
        vis_samples: list[dict[str, Any]] = []
        for s in samples:
            m = torch.as_tensor(s["hand_contact_mask"]).bool().view(-1)
            if int(m.numel()) != int(num_surface_points):
                raise ValueError(
                    f"{robot_name}: inconsistent real mask length {m.numel()} vs {num_surface_points}"
                )
            real_masks_list.append(m)
            if s.get("surface_template_hash") is not None:
                real_template_hashes.add(str(s["surface_template_hash"]))
            if bool(args.vis_components):
                if "hand_surface_points" in s:
                    pts = torch.as_tensor(s["hand_surface_points"]).float().view(-1, 3)
                else:
                    q_tmp = torch.as_tensor(s["q"]).float().view(-1)
                    q_tmp = q_tmp[: model.dof]
                    pts, _ = model.get_surface_points_normals(q_tmp)
                    pts = pts.detach().cpu().float()
                q_vis = torch.as_tensor(s["q"]).float().view(-1)
                if int(q_vis.numel()) > int(model.dof):
                    q_vis = q_vis[: model.dof]
                if int(q_vis.numel()) != int(model.dof):
                    raise ValueError(
                        f"{robot_name}: q dim mismatch in sample (got {q_vis.numel()}, expected {model.dof})"
                    )
                vis_samples.append(
                    {
                        "q": q_vis.detach().cpu(),
                        "mask": m.detach().cpu(),
                        "points": pts.detach().cpu(),
                    }
                )
        real_masks_t = torch.stack(real_masks_list, dim=0).bool()

        if len(real_template_hashes) > 1:
            raise RuntimeError(
                f"{robot_name}: inconsistent surface_template_hash in extracted masks: {sorted(real_template_hashes)}"
            )
        if len(real_template_hashes) == 1:
            extracted_hash = next(iter(real_template_hashes))
            if extracted_hash != model_template_hash:
                raise RuntimeError(
                    f"{robot_name}: template hash mismatch ({extracted_hash} != {model_template_hash}). "
                    "Regenerate extracted contacts with current code."
                )

        sampler_state = model.fit_contact_mask_sampler(real_masks_t)
        comp_range = sampler_state.get("component_range", torch.tensor([1, 4], dtype=torch.long))
        comp_lo = int(comp_range[0].item())
        comp_hi = int(comp_range[1].item())

        counts = real_masks_t.sum(dim=1).float()
        out["robots"][robot_name] = {
            "robot_model_name": resolved_robot_name,
            "num_surface_points": int(num_surface_points),
            "surface_template_hash": model_template_hash,
            "component_range": [int(comp_lo), int(comp_hi)],
            "num_real_samples": int(real_masks_t.shape[0]),
            "real_count_mean": float(counts.mean().item()),
            "real_count_std": float(counts.std(unbiased=False).item()),
        }
        print(
            f"[{robot_name}] model={resolved_robot_name} n_real={real_masks_t.shape[0]} "
            f"component_range={[comp_lo, comp_hi]} template_hash={model_template_hash[:12]}"
        )

        if bool(args.vis_components):
            comp_samples: list[dict[str, Any]] = []
            neighbors = model.surface_graph_neighbors
            for s_vis in vis_samples:
                labels, n_comp = _mask_component_labels(s_vis["mask"], neighbors)
                comp_samples.append(
                    {
                        "q": s_vis["q"],
                        "points": s_vis["points"],
                        "mask": s_vis["mask"],
                        "component_labels": labels,
                        "num_components": int(n_comp),
                    }
                )
            vis_payload[robot_name] = {"model": model, "samples": comp_samples}

    output_yaml = os.path.abspath(args.output_yaml)
    os.makedirs(os.path.dirname(output_yaml), exist_ok=True)
    with open(output_yaml, "w", encoding="utf-8") as f:
        yaml.safe_dump(out, f, sort_keys=False)
    print(f"[saved] {output_yaml}")

    if bool(args.vis_components):
        _visualize_contact_components(
            vis_payload=vis_payload,
            host=str(args.vis_host),
            port=int(args.vis_port),
            point_size=float(args.vis_point_size),
            hand_opacity=float(args.vis_hand_opacity),
        )


if __name__ == "__main__":
    main()
