from __future__ import annotations

import argparse
import os
import sys
import time
from datetime import datetime
from typing import Any

import yaml
import torch


THIS_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(THIS_DIR)


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Infer contact-sampler hyperparameters from extracted real contact masks and "
            "save them into a YAML file."
        )
    )
    parser.add_argument(
        "--real-masks-path",
        type=str,
        default=os.path.join(PROJECT_ROOT, "contact_gen", "contact_points_validate.pt"),
        help="Path to payload generated by extract_contact_points.py",
    )
    parser.add_argument(
        "--robot-names",
        type=str,
        nargs="*",
        default=["allegro", "barrett", "ezgripper", "robotiq_3finger", "shadowhand"],
        help="Robots to infer. Must match robot_name in extracted payload samples.",
    )
    parser.add_argument(
        "--num-surface-points",
        type=int,
        default=-1,
        help="Whole-hand point count. -1 means infer from real masks per robot.",
    )
    parser.add_argument(
        "--max-real-per-robot",
        type=int,
        default=-1,
        help="Optional cap for real-mask samples per robot; -1 for all.",
    )
    parser.add_argument(
        "--output-yaml",
        type=str,
        default=os.path.join(PROJECT_ROOT, "contact_gen", "contact_sampler_hparams.yaml"),
        help="Output YAML path.",
    )
    parser.add_argument(
        "--vis-graph",
        action="store_true",
        help="Visualize surface connectivity graph after inferring hyperparameters.",
    )
    parser.add_argument("--vis-host", type=str, default="127.0.0.1")
    parser.add_argument("--vis-port", type=int, default=8092)
    parser.add_argument("--vis-point-size", type=float, default=0.002)
    parser.add_argument("--vis-hand-opacity", type=float, default=0.35)
    return parser


def _resolve_robot_model_name(robot_name: str, asset_names: set[str], hint: str | None) -> str:
    if hint is not None and hint in asset_names:
        return hint
    if robot_name in asset_names:
        return robot_name
    preferred = {
        "allegro": ["dro/allegro/allegro_hand_left_extended", "dro/allegro/allegro_hand_left"],
        "barrett": ["dro/barrett/model_extended", "dro/barrett/model"],
        "ezgripper": ["dro/ezgripper/ezgripper_extended", "dro/ezgripper/ezgripper"],
        "robotiq_3finger": [
            "dro/urdf/robotiq_3finger_description_extended",
            "dro/urdf/robotiq_3finger_description",
        ],
        "shadowhand": ["dro/shadowhand/shadow_hand_right_extended", "dro/shadowhand/shadow_hand_right"],
    }
    for c in preferred.get(robot_name, []):
        if c in asset_names:
            return c
    candidates = [k for k in asset_names if (f"/{robot_name}/" in k) or (robot_name in k)]
    if len(candidates) == 0:
        raise KeyError(f"Cannot resolve robot model for '{robot_name}'")
    candidates = sorted(
        candidates,
        key=lambda x: (int(x.startswith("dro/")), int("extended" in x), int("right" in x), -len(x)),
        reverse=True,
    )
    return candidates[0]


def _visualize_surface_graph(
    models: dict[str, Any],
    host: str,
    port: int,
    point_size: float,
    hand_opacity: float,
) -> None:
    import numpy as np
    import viser

    if len(models) == 0:
        raise RuntimeError("No models available for graph visualization.")

    robot_names = sorted(models.keys())
    max_points = max(int(models[n].surface_template_points_local.shape[0]) for n in robot_names)
    max_points = max(1, max_points)

    server = viser.ViserServer(host=host, port=int(port))
    robot_slider = server.gui.add_slider(
        "robot_index",
        min=0,
        max=max(0, len(robot_names) - 1),
        step=1,
        initial_value=0,
    )
    point_slider = server.gui.add_slider(
        "point_index",
        min=0,
        max=max_points - 1,
        step=1,
        initial_value=0,
    )
    mesh_mode_slider = server.gui.add_slider(
        "mesh_mode (0=none,1=simplified,2=original,3=both)",
        min=0,
        max=3,
        step=1,
        initial_value=3,
    )
    normal_scale_slider = server.gui.add_slider(
        "normal_scale",
        min=0.0,
        max=0.03,
        step=0.0005,
        initial_value=0.0,
    )

    def _render() -> None:
        ridx = int(robot_slider.value)
        robot_name = robot_names[ridx]
        model = models[robot_name]

        q = model.get_canonical_q().detach().clone()
        if hasattr(model, "base_translation_indices") and len(model.base_translation_indices) > 0:
            q[model.base_translation_indices] = 0.0

        points, normals = model.get_surface_points_normals(q)
        points = points.detach().cpu()
        normals = normals.detach().cpu()
        n = int(points.shape[0])
        if n == 0:
            return
        pidx = int(max(0, min(int(point_slider.value), n - 1)))

        graph = model.surface_graph_neighbors
        neighbors = graph[pidx] if pidx < len(graph) else []

        colors = np.zeros((n, 3), dtype=np.float32)
        colors[:, 0] = 0.25
        colors[:, 1] = 0.62
        colors[:, 2] = 1.00

        mesh_mode = int(mesh_mode_slider.value)
        show_simplified = mesh_mode in (1, 3)
        show_original = mesh_mode in (2, 3)

        simplified_mesh = getattr(model, "surface_union_mesh_canonical", None)
        if simplified_mesh is None:
            simplified_mesh = model.get_trimesh_q(q)["visual"]

        original_mesh = model.get_trimesh_q(q)["visual"]

        center_candidates: list[torch.Tensor] = []
        if show_simplified and len(simplified_mesh.vertices) > 0:
            center_candidates.append(torch.tensor(simplified_mesh.vertices, dtype=torch.float32))
        if show_original and len(original_mesh.vertices) > 0:
            center_candidates.append(torch.tensor(original_mesh.vertices, dtype=torch.float32))
        if len(center_candidates) == 0:
            center = points.mean(dim=0, keepdim=True)
        else:
            center = torch.cat(center_candidates, dim=0).mean(dim=0, keepdim=True)

        points_vis = points - center
        if len(neighbors) > 0:
            neigh_np = np.array(neighbors, dtype=np.int64)
            neigh_np = neigh_np[(neigh_np >= 0) & (neigh_np < n)]
            colors[neigh_np, :] = np.array([1.00, 0.85, 0.20], dtype=np.float32)
        colors[pidx, :] = np.array([1.00, 0.20, 0.20], dtype=np.float32)

        server.scene.add_point_cloud(
            name="surface_graph_points",
            points=points_vis.numpy().astype(np.float32),
            colors=colors,
            point_size=float(point_size),
            point_shape="circle",
        )

        if len(neighbors) > 0:
            neigh_idx = np.array(neighbors, dtype=np.int64)
            neigh_idx = neigh_idx[(neigh_idx >= 0) & (neigh_idx < n)]
            neigh_pts = points_vis[torch.as_tensor(neigh_idx, dtype=torch.long)]
            anchor = points_vis[pidx].unsqueeze(0).repeat(neigh_pts.shape[0], 1)
            seg = torch.stack([anchor, neigh_pts], dim=1).numpy().astype(np.float32)
            server.scene.add_line_segments(
                name="surface_graph_edges",
                points=seg,
                colors=(1.0, 0.25, 0.25),
                line_width=2.0,
            )
        else:
            server.scene.add_line_segments(
                name="surface_graph_edges",
                points=np.zeros((0, 2, 3), dtype=np.float32),
                colors=(1.0, 0.25, 0.25),
                line_width=2.0,
            )

        normal_scale = float(normal_scale_slider.value)
        if normal_scale > 0.0:
            end = points_vis + normals * normal_scale
            seg = torch.stack([points_vis, end], dim=1).numpy().astype(np.float32)
            server.scene.add_line_segments(
                name="surface_normals",
                points=seg,
                colors=(0.30, 0.95, 0.95),
                line_width=1.5,
            )
            query_seg = torch.stack([points_vis[pidx], end[pidx]], dim=0).unsqueeze(0).numpy().astype(np.float32)
            server.scene.add_line_segments(
                name="query_normal",
                points=query_seg,
                colors=(1.0, 0.05, 0.95),
                line_width=3.0,
            )
        else:
            server.scene.add_line_segments(
                name="surface_normals",
                points=np.zeros((0, 2, 3), dtype=np.float32),
                colors=(0.0, 0.0, 0.0),
                line_width=0.0,
            )
            server.scene.add_line_segments(
                name="query_normal",
                points=np.zeros((0, 2, 3), dtype=np.float32),
                colors=(0.0, 0.0, 0.0),
                line_width=0.0,
            )

        if show_simplified:
            v = torch.tensor(simplified_mesh.vertices, dtype=torch.float32) - center
            f = torch.tensor(simplified_mesh.faces, dtype=torch.int32)
            server.scene.add_mesh_simple(
                name="hand_mesh_simplified",
                vertices=v.numpy(),
                faces=f.numpy(),
                color=(0.20, 0.78, 0.35),
                opacity=float(hand_opacity),
            )
        else:
            server.scene.add_mesh_simple(
                name="hand_mesh_simplified",
                vertices=np.zeros((0, 3), dtype=np.float32),
                faces=np.zeros((0, 3), dtype=np.int32),
                color=(0.0, 0.0, 0.0),
                opacity=0.0,
            )

        if show_original:
            v = torch.tensor(original_mesh.vertices, dtype=torch.float32) - center
            f = torch.tensor(original_mesh.faces, dtype=torch.int32)
            server.scene.add_mesh_simple(
                name="hand_mesh_original",
                vertices=v.numpy(),
                faces=f.numpy(),
                color=(0.72, 0.72, 0.72),
                opacity=float(0.6 * hand_opacity),
            )
        else:
            server.scene.add_mesh_simple(
                name="hand_mesh_original",
                vertices=np.zeros((0, 3), dtype=np.float32),
                faces=np.zeros((0, 3), dtype=np.int32),
                color=(0.0, 0.0, 0.0),
                opacity=0.0,
            )

        print(
            f"[graph-vis] robot={robot_name} point={pidx} degree={len(neighbors)} mesh_mode={mesh_mode} "
            f"normal_scale={normal_scale:.4f} "
            f"num_points={n}"
        )

    @robot_slider.on_update
    def _(_: Any) -> None:
        _render()

    @point_slider.on_update
    def _(_: Any) -> None:
        _render()

    @mesh_mode_slider.on_update
    def _(_: Any) -> None:
        _render()

    @normal_scale_slider.on_update
    def _(_: Any) -> None:
        _render()

    _render()
    print(f"Graph viewer URL: http://{host}:{port}")
    print("Use sliders: robot_index and point_index.")
    while True:
        time.sleep(1.0)


def main() -> None:
    args = _build_parser().parse_args()
    real_masks_path = os.path.abspath(args.real_masks_path)
    if not os.path.exists(real_masks_path):
        raise FileNotFoundError(f"--real-masks-path not found: {real_masks_path}")

    payload_real = torch.load(real_masks_path, map_location="cpu")
    if "samples" not in payload_real:
        raise KeyError(f"Expected 'samples' in {real_masks_path}")
    real_samples = list(payload_real["samples"])
    if len(real_samples) == 0:
        raise RuntimeError(f"No samples in {real_masks_path}")

    selected_robots = set(args.robot_names)
    by_robot: dict[str, list[dict[str, Any]]] = {r: [] for r in args.robot_names}
    for s in real_samples:
        robot_name = str(s["robot_name"])
        if robot_name not in selected_robots:
            continue
        by_robot[robot_name].append(s)

    sys.path.append(PROJECT_ROOT)
    from robot_model.robot_model import create_robot_model, discover_robot_assets  # type: ignore

    assets_meta = discover_robot_assets()
    asset_names = set(assets_meta.keys())

    out: dict[str, Any] = {
        "meta": {
            "created_at": datetime.now().isoformat(timespec="seconds"),
            "real_masks_path": real_masks_path,
            "source": "extract_contact_points.py",
            "method": "fit from real masks only; used later for data-less random generation",
        },
        "robots": {},
    }
    vis_models: dict[str, Any] = {}

    for robot_name in args.robot_names:
        samples = by_robot.get(robot_name, [])
        if len(samples) == 0:
            print(f"[skip] {robot_name}: no real-mask samples found")
            continue
        if int(args.max_real_per_robot) > 0:
            samples = samples[: int(args.max_real_per_robot)]

        first_len = int(torch.as_tensor(samples[0]["hand_contact_mask"]).numel())
        if int(args.num_surface_points) > 0 and int(args.num_surface_points) != first_len:
            raise ValueError(
                f"{robot_name}: --num-surface-points={args.num_surface_points} "
                f"does not match real mask length={first_len}"
            )
        num_surface_points = first_len if int(args.num_surface_points) <= 0 else int(args.num_surface_points)

        hint = samples[0].get("robot_model_name", None)
        resolved_robot_name = _resolve_robot_model_name(robot_name, asset_names, None if hint is None else str(hint))
        model = create_robot_model(
            robot_name=resolved_robot_name,
            device=torch.device("cpu"),
            num_points=int(num_surface_points),
        )
        vis_models[robot_name] = model
        model_template_hash = model.get_surface_template_hash()

        real_template_hashes = set()
        real_masks_list = []
        for s in samples:
            m = torch.as_tensor(s["hand_contact_mask"]).bool().view(-1)
            if int(m.numel()) != int(num_surface_points):
                raise ValueError(
                    f"{robot_name}: inconsistent real mask length {m.numel()} vs {num_surface_points}"
                )
            real_masks_list.append(m)
            if s.get("surface_template_hash") is not None:
                real_template_hashes.add(str(s["surface_template_hash"]))
        real_masks_t = torch.stack(real_masks_list, dim=0).bool()

        if len(real_template_hashes) > 1:
            raise RuntimeError(
                f"{robot_name}: inconsistent surface_template_hash in extracted masks: {sorted(real_template_hashes)}"
            )
        if len(real_template_hashes) == 1:
            extracted_hash = next(iter(real_template_hashes))
            if extracted_hash != model_template_hash:
                raise RuntimeError(
                    f"{robot_name}: template hash mismatch ({extracted_hash} != {model_template_hash}). "
                    "Regenerate extracted contacts with current code."
                )

        sampler_state = model.fit_contact_mask_sampler(real_masks_t)
        comp_range = sampler_state.get("component_range", torch.tensor([1, 4], dtype=torch.long))
        comp_lo = int(comp_range[0].item())
        comp_hi = int(comp_range[1].item())

        counts = real_masks_t.sum(dim=1).float()
        out["robots"][robot_name] = {
            "robot_model_name": resolved_robot_name,
            "num_surface_points": int(num_surface_points),
            "surface_template_hash": model_template_hash,
            "component_range": [int(comp_lo), int(comp_hi)],
            "num_real_samples": int(real_masks_t.shape[0]),
            "real_count_mean": float(counts.mean().item()),
            "real_count_std": float(counts.std(unbiased=False).item()),
        }
        print(
            f"[{robot_name}] model={resolved_robot_name} n_real={real_masks_t.shape[0]} "
            f"component_range={[comp_lo, comp_hi]} template_hash={model_template_hash[:12]}"
        )

    output_yaml = os.path.abspath(args.output_yaml)
    os.makedirs(os.path.dirname(output_yaml), exist_ok=True)
    with open(output_yaml, "w", encoding="utf-8") as f:
        yaml.safe_dump(out, f, sort_keys=False)
    print(f"[saved] {output_yaml}")

    if bool(args.vis_graph):
        _visualize_surface_graph(
            models=vis_models,
            host=str(args.vis_host),
            port=int(args.vis_port),
            point_size=float(args.vis_point_size),
            hand_opacity=float(args.vis_hand_opacity),
        )


if __name__ == "__main__":
    main()
