from __future__ import annotations

import argparse
import os
import sys
import time
from typing import Any

import torch
import viser


THIS_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(THIS_DIR)


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Visualize sampled contact masks and simulated object patches."
    )
    parser.add_argument(
        "--sampled-path",
        type=str,
        required=True,
        help="Path to <robot>_random_masks.pt generated by generate_random_contact_masks.py",
    )
    parser.add_argument("--host", type=str, default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8080)
    parser.add_argument("--contact-point-size", type=float, default=0.004)
    parser.add_argument("--patch-point-size", type=float, default=0.003)
    parser.add_argument("--hand-opacity", type=float, default=0.75)
    return parser


def _to_tensor(x: Any) -> torch.Tensor:
    if torch.is_tensor(x):
        return x.detach().float().cpu()
    return torch.tensor(x, dtype=torch.float32)


def _empty_points() -> torch.Tensor:
    return torch.zeros((0, 3), dtype=torch.float32)


def _empty_mesh() -> tuple[torch.Tensor, torch.Tensor]:
    return torch.zeros((0, 3), dtype=torch.float32), torch.zeros((0, 3), dtype=torch.int32)


def main() -> None:
    args = _build_parser().parse_args()
    sampled_path = os.path.abspath(args.sampled_path)
    if not os.path.exists(sampled_path):
        raise FileNotFoundError(f"sampled file not found: {sampled_path}")

    payload = torch.load(sampled_path, map_location="cpu")
    vis_samples = list(payload.get("visualization_samples", []))
    if len(vis_samples) == 0:
        raise RuntimeError(
            "No visualization samples found. Re-run generation with --save-visualization-samples > 0."
        )

    meta = payload.get("meta", {})
    robot_name = str(meta.get("robot_name", vis_samples[0].get("robot_name", "unknown")))
    robot_model_name = str(meta.get("robot_model_name", vis_samples[0].get("robot_model_name", robot_name)))
    num_surface_points = int(meta.get("num_surface_points", 256))

    sys.path.append(PROJECT_ROOT)
    from robot_model.robot_model import create_robot_model  # type: ignore

    model = create_robot_model(
        robot_name=robot_model_name,
        device=torch.device("cpu"),
        num_points=num_surface_points,
    )
    model_template_hash = model.get_surface_template_hash()
    expected_template_hash = meta.get("surface_template_hash", None)
    if expected_template_hash is not None and str(expected_template_hash) != model_template_hash:
        print(
            "[warn] surface template hash mismatch: "
            f"payload={expected_template_hash} model={model_template_hash}"
        )

    server = viser.ViserServer(host=args.host, port=int(args.port))
    sample_slider = server.gui.add_slider(
        label="sample_index",
        min=0,
        max=max(0, len(vis_samples) - 1),
        step=1,
        initial_value=0,
    )
    mode_slider = server.gui.add_slider(
        label="vis_mode (0=points,1=points+hand,2=points+patches,3=all)",
        min=0,
        max=3,
        step=1,
        initial_value=3,
    )

    def _render(idx: int, vis_mode: int) -> None:
        sample = vis_samples[idx]
        q = _to_tensor(sample["q"])
        hand_points = _to_tensor(sample.get("hand_points", _empty_points()))
        hand_mask = sample.get("hand_contact_mask", None)
        hand_contact_points = sample.get("hand_contact_points", None)
        if hand_points.ndim != 2 or hand_points.shape[0] == 0:
            hand_points, _ = model.get_surface_points_normals(q)
            hand_points = hand_points.detach().cpu()
        if hand_contact_points is None:
            if hand_mask is not None and hand_points.ndim == 2:
                mask_t = torch.as_tensor(hand_mask).bool()
                if mask_t.numel() == hand_points.shape[0]:
                    hand_contact_points_t = hand_points[mask_t]
                else:
                    hand_contact_points_t = _empty_points()
            else:
                hand_contact_points_t = _empty_points()
        else:
            hand_contact_points_t = _to_tensor(hand_contact_points)

        object_patch_points = _to_tensor(sample.get("object_patch_points", _empty_points()))

        has_contacts = hand_contact_points_t.ndim == 2 and hand_contact_points_t.shape[0] > 0
        has_patches = object_patch_points.ndim == 2 and object_patch_points.shape[0] > 0

        # 0: points only, 1: points+hand, 2: points+patches, 3: all
        show_points = vis_mode in (0, 1, 2, 3)
        show_hand = vis_mode in (1, 3)
        show_patches = vis_mode in (2, 3)

        server.scene.add_point_cloud(
            "contact_points",
            hand_contact_points_t.numpy() if has_contacts and show_points else _empty_points().numpy(),
            point_size=float(args.contact_point_size),
            point_shape="circle",
            colors=(255, 90, 90),
            visible=bool(has_contacts and show_points),
        )
        server.scene.add_point_cloud(
            "object_patch_points",
            object_patch_points.numpy() if has_patches and show_patches else _empty_points().numpy(),
            point_size=float(args.patch_point_size),
            point_shape="circle",
            colors=(80, 230, 120),
            visible=bool(has_patches and show_patches),
        )

        if show_hand:
            hand_mesh = model.get_trimesh_q(q)["visual"]
            server.scene.add_mesh_simple(
                "hand_mesh",
                torch.tensor(hand_mesh.vertices, dtype=torch.float32).numpy(),
                torch.tensor(hand_mesh.faces, dtype=torch.int32).numpy(),
                color=(102, 192, 255),
                opacity=float(args.hand_opacity),
                visible=True,
            )
        else:
            v, f = _empty_mesh()
            server.scene.add_mesh_simple(
                "hand_mesh",
                v.numpy(),
                f.numpy(),
                color=(0, 0, 0),
                opacity=0.0,
                visible=False,
            )

        print(
            f"[sample {idx}] robot={robot_name} contacts={int(has_contacts and hand_contact_points_t.shape[0])} "
            f"patch_points={int(has_patches and object_patch_points.shape[0])} mode={vis_mode}"
        )

    sample_slider.on_update(lambda _: _render(int(sample_slider.value), int(mode_slider.value)))
    mode_slider.on_update(lambda _: _render(int(sample_slider.value), int(mode_slider.value)))
    _render(0, int(mode_slider.value))
    print(f"Viewer URL: http://{args.host}:{args.port}")
    while True:
        time.sleep(1.0)


if __name__ == "__main__":
    main()
